### ISSUE TITLE
Error Command?

### ISSUE THREAD

**Issue by treefroog** [ImperialNewsNetwork/inn-bot#2]
I was reading Discord's bot guidelines and one of them is to not have an error statement like INN Bot does whenever you type something random like !tapir because of bot conflicts on servers. [guidlines](http://i.imgur.com/dHvoX8I.png). I'm not sure if this applies to INN Bot but it makes sense so that other people can have bots that use the "!" as a trigger but not have INN Bot tell them it's an invalid command, and the bot they want to use respond.

**Comment by davidtwco** [comment]
Hi @treefroog,

Thanks a ton for pointing this out - I've went ahead and removed that message, I'll update the live bot momentarily.
