### ISSUE TITLE
When someone says 'uee' in chat the bot replies with the '!stats' prompt

### ISSUE THREAD

**Issue by treefroog** [ImperialNewsNetwork/inn-bot#4]
No matter what channel a user says uee INNbot replies with the same message as if someone says '!stats'
![inn_borked](https://cloud.githubusercontent.com/assets/18294397/15344830/eb5df3f6-1c77-11e6-981a-13c8bde98fb6.png)

**Comment by davidtwco** [comment]
Hi, 

Thanks for the report. I've just confirmed this happening - I'll work on a fix and reply here when it's deployed. 


Thanks.

**Comment by davidtwco** [comment]
I've just pushed a commit that fixes this - it will be deployed momentarily, thanks for the report @treefroog!

**Comment by davidtwco** [comment]
Deployed.
