### ISSUE TITLE
Logging deleted messages.

### ISSUE THREAD

**Issue by Bartti** [ImperialNewsNetwork/inn-bot#7]
!log command to make the bot start logging all **deleted** messages and output them, along with name of the author of the deleted message into a separate channel, for example "#deleted_logs". If the channel does not exist, output an error message.
!log requires "Manage Server" permission.

**Comment by davidtwco** [comment]
This would rely on some form of persistence so commands can maintain state between restarts - currently there isn't any, so `!stats` doesn't persist the funding history difference between restarts and the deleted message history is lost between restarts. This is something I've wanted to do as it opens up more possibilities for useful commands, like the Reminder Command (#3).

I'll think about this and start work on it this weekend. I expect the syntax will end up being `!log #deleted_logs` where you include the channel name.

**Comment by davidtwco** [comment]
Introduced this without using bot configuration (ie. no command persistence) in d588b1fbff7e7c8a9000d6e200850f277deede50.
